### ISSUE TITLE
I have added temperature of my serveur

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/ServerMonitor#2]
![image](https://user-images.githubusercontent.com/32466950/34582852-b6e01970-f195-11e7-85f8-5bd49cbd4648.png)

**Comment by DanielnetoDotCom** [comment]
this is great, make a pull request if you want

**Comment by gamersalpha** [comment]
Hello, 
it's the first time i do that, hope it's OK

**Comment by DanielnetoDotCom** [comment]
it was great
